import os
import json
import xml.etree.ElementTree as ET

def get_version_from_common_props():
    """ common.props dosyasındaki versiyon bilgilerini çeker. """
    tree = ET.parse("common.props")
    root = tree.getroot()
    
    version = root.find(".//Version").text
    leptonx_version = root.find(".//LeptonXVersion").text

    return version, leptonx_version

def update_latest_versions():
    version, leptonx_version = get_version_from_common_props()

    # Eğer versiyon "preview" içeriyorsa PR oluşturma (sadece stable versiyonlar için)
    if "preview" in version or "rc" in version:
        return False

    with open("latest-versions.json", "r") as f:
        latest_versions = json.load(f)

    # Yeni versiyon bilgisini en üst sıraya ekle
    new_version_entry = {
        "version": version,
        "releaseDate": "",
        "type": "stable",
        "message": "",
        "leptonx": {
            "version": leptonx_version
        }
    }
    
    latest_versions.insert(0, new_version_entry)  # Yeni versiyonu en üste ekliyoruz

    with open("latest-versions.json", "w") as f:
        json.dump(latest_versions, f, indent=2)

    return True
